version: "3.3"
services:
  db:
    container_name: mysqldb
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: wordcloud
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
  nodeapp:
    container_name: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
      - 3001:3001