version: "3"

services:
  app:
    image: wordcloudgeneratorregistry.azurecr.io/my-vue-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["npm", "run", "serve"]